// TypesFromSerializers CacheKey b6b295553bd7dd6eecba03c1d3a3e508
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface CompaniesEdit {
      id: number
      name?: string
      slug?: string
    }
  }
}
