// TypesFromSerializers CacheKey a63e57760f039eef61099cc45e4962af
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface CompaniesFormData {
      id?: number
      name?: string
      slug?: string
    }
  }
}
