// TypesFromSerializers CacheKey 0f7692d98f28313f4e0cc6efde549764
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface CompaniesIndex {
      id: number
      created_at: string | Date
      name?: string
      slug?: string
      updated_at: string | Date
    }
  }
}
