// TypesFromSerializers CacheKey 7a09f324f5a525896d80925a34ea5e2b
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface CompaniesShow {
      id: number
      created_at: string | Date
      name?: string
      slug?: string
      updated_at: string | Date
    }
  }
}
