// TypesFromSerializers CacheKey 9608f396bca896b1f2546211801fb226
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PeriodsEdit {
      id: number
      end_time: Date
      name: string
      start_time: Date
    }
  }
}
