// TypesFromSerializers CacheKey e8a6247de960c7d41dba92b7892206cb
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PeriodsFormData {
      id?: number
      end_time: string
      name: string
      start_time: string
    }
  }
}
