// TypesFromSerializers CacheKey a40fece63bea3b0e857aff0bc5b375c6
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PeriodsFormData {
      id?: number
      end_time: Date
      name: string
      start_time: Date
    }
  }
}
