// TypesFromSerializers CacheKey 1cffd390d85133360b833157f61d18c1
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PeriodsIndex {
      id: number
      end_time: string
      name: string
      start_time: string
    }
  }
}
