// TypesFromSerializers CacheKey e759f4eb480008fbefd896d408bcea8f
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PeriodsIndex {
      id: number
      end_time: Date
      name: string
      start_time: Date
    }
  }
}
