// TypesFromSerializers CacheKey 4a428367557569d89cfea7c9a1d6ab4d
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PeriodsOptions {
      id: number
      name: string
    }
  }
}
