// TypesFromSerializers CacheKey c99df6ceaca95171111d469b9843eb24
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PeriodsShow {
      id: number
      end_time: Date
      name: string
      start_time: Date
    }
  }
}
