// TypesFromSerializers CacheKey 295e3142d4e7290cbbc71aa27f5dcf52
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PeriodsShow {
      id: number
      end_time: string
      name: string
      start_time: string
    }
  }
}
