// TypesFromSerializers CacheKey 9d78a4e58d307f1f70bda9c520a471c7
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Company {
      id?: number
      created_at: string | Date
      name?: string
      slug?: string
      updated_at: string | Date
    }
  }
}
