// TypesFromSerializers CacheKey dc2d4c6b9402caa726fee70e6dcc06c1
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Outlet {
      id?: number
      created_at: string | Date
      name: string
      short?: string
      slug?: string
      updated_at: string | Date
    }
  }
}
