// TypesFromSerializers CacheKey 97bfbc4ac0e4d2b27e7a80965fee201b
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Period {
      id?: number
      end_time?: unknown
      name?: string
      start_time?: unknown
    }
  }
}
