// TypesFromSerializers CacheKey f4f44af632bca5cffbae8a26fe45dbc3
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Person {
      id?: number
      active: boolean
      created_at: string | Date
      first_name?: string
      last_name?: string
      name: string
      updated_at: string | Date
      user_id?: number
    }
  }
}
