// TypesFromSerializers CacheKey ce396ee6ea854609f46f1e4383e2e566
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface Position {
      id?: number
      created_at: string | Date
      name?: string
      outlet_id: number
      slug?: string
      updated_at: string | Date
    }
  }
}
