// TypesFromSerializers CacheKey f69154a2ed276695578c987a413ebe80
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Period from './Period'
import type ServiceTemplate from './ServiceTemplate'

declare global {
  namespace Schema {
    interface Service {
      id?: number
      date: string | Date
      period: Period
      service_template: ServiceTemplate
    }
  }
}
