// TypesFromSerializers CacheKey 9686b746c81bb89f90478ce23bb7bfe2
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ServiceTemplate {
      id?: number
      created_at: string | Date
      description?: string
      name?: string
      updated_at: string | Date
    }
  }
}
