// TypesFromSerializers CacheKey 87e9d8ca69c008dcd8ec78e99f9d8cd7
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface ServiceTemplate {
      id?: number
      description?: string
      name?: string
    }
  }
}
