// TypesFromSerializers CacheKey c09a8c0b72738a391b59cc6a118b42f9
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Period from './Period'
import type ServiceTemplate from './ServiceTemplate'

declare global {
  namespace Schema {
    interface Service {
      id?: number
      created_at: string | Date
      date: string
      period: Period
      service_template: ServiceTemplate
      updated_at: string | Date
    }
  }
}
