// TypesFromSerializers CacheKey 6838fff181c8967769af9f5d15846d51
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Person from './Person'
import type Position from './Position'

declare global {
  namespace Schema {
    interface Shift {
      id?: number
      created_at: string | Date
      end_time?: string | Date
      person: Person
      position: Position
      start_time?: string | Date
      updated_at: string | Date
    }
  }
}
