require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/outlets", type: :request do

  # This should return the minimal set of attributes required to create a valid
  # Outlet. As you add validations to Outlet, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Outlet.create! valid_attributes
      get outlets_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      outlet = Outlet.create! valid_attributes
      get outlet_url(outlet)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_outlet_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      outlet = Outlet.create! valid_attributes
      get edit_outlet_url(outlet)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Outlet" do
        expect {
          post outlets_url, params: { outlet: valid_attributes }
        }.to change(Outlet, :count).by(1)
      end

      it "redirects to the created outlet" do
        post outlets_url, params: { outlet: valid_attributes }
        expect(response).to redirect_to(outlet_url(Outlet.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Outlet" do
        expect {
          post outlets_url, params: { outlet: invalid_attributes }
        }.not_to change(Outlet, :count)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post outlets_url, params: { outlet: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end

    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested outlet" do
        outlet = Outlet.create! valid_attributes
        patch outlet_url(outlet), params: { outlet: new_attributes }
        outlet.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the outlet" do
        outlet = Outlet.create! valid_attributes
        patch outlet_url(outlet), params: { outlet: new_attributes }
        outlet.reload
        expect(response).to redirect_to(outlet_url(outlet))
      end
    end

    context "with invalid parameters" do

      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        outlet = Outlet.create! valid_attributes
        patch outlet_url(outlet), params: { outlet: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end

    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested outlet" do
      outlet = Outlet.create! valid_attributes
      expect {
        delete outlet_url(outlet)
      }.to change(Outlet, :count).by(-1)
    end

    it "redirects to the outlets list" do
      outlet = Outlet.create! valid_attributes
      delete outlet_url(outlet)
      expect(response).to redirect_to(outlets_url)
    end
  end
end
