// TypesFromSerializers CacheKey f9b7ac853b5a6681590a702a18935665
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Person from '../Person'
import type Position from '../Position'

declare global {
  namespace Schema {
    interface ShiftsEdit {
      id: number
      end_time?: string | Date
      person: Person
      position: Position
      start_time?: string | Date
    }
  }
}
