// TypesFromSerializers CacheKey ac7b8f79bace9aee77a9bc7d1297a168
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Person from '../Person'
import type Position from '../Position'

declare global {
  namespace Schema {
    interface ShiftsFormData {
      id?: number
      end_time?: string | Date
      person: Person
      position: Position
      start_time?: string | Date
    }
  }
}
