// TypesFromSerializers CacheKey 17dec274684d9f7df986be0011b95dd6
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Person from '../Person'
import type Position from '../Position'

declare global {
  namespace Schema {
    interface ShiftsIndex {
      id: number
      end_time?: string | Date
      person: Person
      position: Position
      start_time?: string | Date
    }
  }
}
