// TypesFromSerializers CacheKey 1b72b05218824df058c3a2d951da46ab
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Person from '../Person'

declare global {
  namespace Schema {
    interface UsersEdit {
      id: number
      active: boolean
      email: string
      person: Person
    }
  }
}
