// TypesFromSerializers CacheKey e46b252fc1de2e0d7b2d791a533a7a06
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface UsersFormData {
      id?: number
      active: boolean
      email: string
      password: unknown
      password_confirmation: unknown
    }
  }
}
