// TypesFromSerializers CacheKey bee4e4e5ba9ed090b1a61772b116ac0b
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PositionsEdit {
      id: number
      name?: string
      outlet_id: number
      slug?: string
    }
  }
}
