// TypesFromSerializers CacheKey 79aa329001d4a54cc6b90300f9c61a30
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PositionsFormData {
      id?: number
      name?: string
      outlet_id: number
      slug?: string
    }
  }
}
