// TypesFromSerializers CacheKey ed546e882c30307f8286d49ab66a59f2
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PositionsIndex {
      id: number
      created_at: string | Date
      name?: string
      outlet_id: number
      slug?: string
      updated_at: string | Date
    }
  }
}
