// TypesFromSerializers CacheKey a5777cd2415c2911fa909f355c8cd788
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PositionsShow {
      id: number
      created_at: string | Date
      name?: string
      outlet_id: number
      slug?: string
      updated_at: string | Date
    }
  }
}
