// TypesFromSerializers CacheKey 88132a92bbc3ec59a9c2e6130f71d783
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PeopleBasic {
      id: number
      active: boolean
      created_at: string | Date
      first_name?: string
      last_name?: string
      name: string
      updated_at: string | Date
      user_id?: number
    }
  }
}
