// TypesFromSerializers CacheKey 94b77d67571dcae7827aafacc0765017
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type UsersFormData from '../Users/FormData'

declare global {
  namespace Schema {
    interface PeopleEdit {
      id: number
      active: boolean
      first_name?: string
      last_name?: string
      name: string
      user?: UsersFormData
    }
  }
}
