// TypesFromSerializers CacheKey 8c169fd2100e56c7d8f3ca6f7e8d1466
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type UsersFormData from '../Users/FormData'

declare global {
  namespace Schema {
    interface PeopleFormData {
      id?: number
      active: boolean
      first_name?: string
      last_name?: string
      user?: UsersFormData
    }
  }
}
