// TypesFromSerializers CacheKey 0279672014da775e9a7afa30a0ae2da8
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Activity from '../Activity'
import type PersonGroup from '../PersonGroup'
import type User from '../User'

declare global {
  namespace Schema {
    interface PeopleIndex {
      id: number
      active: boolean
      activities: Activity[]
      created_at: string | Date
      first_name?: string
      groups: PersonGroup[]
      last_name?: string
      name: string
      updated_at: string | Date
      user: User
      user_id?: number
    }
  }
}
