// TypesFromSerializers CacheKey 06a129b190d5362ceb348c107c3dd113
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface PeopleOptions {
      id?: number
      name: string
    }
  }
}
