// TypesFromSerializers CacheKey 4f26661de6646fbdcf765f2189ec251a
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Activity from '../Activity'
import type User from '../User'

declare global {
  namespace Schema {
    interface PeopleShow {
      id: number
      active: boolean
      activities: Activity[]
      created_at: string | Date
      first_name?: string
      last_name?: string
      name: string
      updated_at: string | Date
      user: User
      user_id?: number
    }
  }
}
