// TypesFromSerializers CacheKey 99eacc1fd2cdd6f7ff2fbc12ea01df69
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Period from '../Period'
import type ServiceTemplate from '../ServiceTemplate'

declare global {
  namespace Schema {
    interface ServicesEdit {
      id?: number
      date: string
      period: Period
      service_template: ServiceTemplate
    }
  }
}
