// TypesFromSerializers CacheKey 2cb86f9d5351e659a3003c14897b8d88
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Period from '../Period'
import type ServiceTemplate from '../ServiceTemplate'

declare global {
  namespace Schema {
    interface ServicesFormData {
      id?: number
      date: string
      period: Period
      service_template: ServiceTemplate
    }
  }
}
