// TypesFromSerializers CacheKey d4fdb1bca97183590eded6c165502441
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Period from '../Period'
import type ServiceTemplate from '../ServiceTemplate'

declare global {
  namespace Schema {
    interface ServicesFormData {
      id?: number
      date: string | Date
      period: Period
      service_template: ServiceTemplate
    }
  }
}
