// TypesFromSerializers CacheKey 37fdf828b90c55c06c00adf897de5b8a
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Period from '../Period'
import type ServiceTemplate from '../ServiceTemplate'

declare global {
  namespace Schema {
    interface ServicesIndex {
      id?: unknown
      date: unknown
      period: Period
      service_template: ServiceTemplate
    }
  }
}
