// TypesFromSerializers CacheKey bd25c59533700dbd52e92a1a7dde773a
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Period from '../Period'
import type ServiceTemplate from '../ServiceTemplate'

declare global {
  namespace Schema {
    interface ServicesIndex {
      id?: number
      date: string
      period: Period
      service_template: ServiceTemplate
    }
  }
}
