// TypesFromSerializers CacheKey 8fa6360dc18fe2640ceb871591f6cde0
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Period from '../Period'
import type ServiceTemplate from '../ServiceTemplate'

declare global {
  namespace Schema {
    interface ServicesShow {
      id: unknown
      date: unknown
      period: Period
      service_template: ServiceTemplate
    }
  }
}
