// TypesFromSerializers CacheKey 671a4c97c38cad7812169d8a1d2c87c1
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type Period from '../Period'
import type ServiceTemplate from '../ServiceTemplate'

declare global {
  namespace Schema {
    interface ServicesShow {
      id: number
      date: string | Date
      period: Period
      service_template: ServiceTemplate
    }
  }
}
