// TypesFromSerializers CacheKey 66eaed0e2ab823e36ecd3fb7d2348309
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
import type PeriodsShow from '../Periods/Show'
import type ServiceTemplate from '../ServiceTemplate'

declare global {
  namespace Schema {
    interface ServicesShow {
      id: number
      date: string
      period: PeriodsShow
      service_template: ServiceTemplate
    }
  }
}
