// TypesFromSerializers CacheKey 3b2650e6f5736aeca9ac7c2f4e25af95
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface OutletsEdit {
      id: number
      name: string
      short?: string
      slug?: string
    }
  }
}
