// TypesFromSerializers CacheKey 89d126673c1effc7a8947633e7082e90
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface OutletsFormData {
      id?: number
      name: string
      short?: string
      slug?: string
    }
  }
}
