// TypesFromSerializers CacheKey 09422f49b031e11b49edce45eaad828c
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface OutletsIndex {
      id: number
      created_at: string | Date
      name: string
      short?: string
      slug?: string
      updated_at: string | Date
    }
  }
}
