// TypesFromSerializers CacheKey 13ade53a4e5c928166196505b4ca766a
//
// DO NOT MODIFY: This file was automatically generated by TypesFromSerializers.
export {}

declare global {
  namespace Schema {
    interface OutletsShow {
      id: number
      created_at: string | Date
      name: string
      short?: string
      slug?: string
      updated_at: string | Date
    }
  }
}
